[pytest]
# Informe a pasta onde o código fonte reside (sem o ponto no início)
# Isso permite que 'from services.game_service...' funcione direto
pythonpath = src

# Define onde o pytest deve procurar os testes
testpaths = tests

# Padrões de descoberta (garante que ele ache seus arquivos atuais)
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Opções extras:
# -v: Verbose (mostra o nome de cada teste)
# -ra: Mostra um resumo de falhas/erros ao final
# --tb=short: Deixa o log de erro mais limpo para ler no terminal
addopts = -v -ra --tb=short